version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
      - "mysql:db"
    ports:
      - "3380:80"
    networks:
      - laravel

  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7
    environment:
      SERVICE_NAME: "mysql"
      MYSQL_ROOT_NAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
